version: "3.7"
services:
  mongodb:
    image: mongo
    ports:
      - 8081:27017
    volumes:
      - ./db:/data/db
  case:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
